import Head from "next/head";
import styles from "styles/Home.module.scss";
import DefaultLayout from "../../layouts/DefaultLayout";
import { useState } from "react";
import ChatArea from "../../components/ChatSection/ChatArea";

export default function Home() {
  const [content, setContent] = useState("");
  const [queries, setQueries] = useState([]);
  return (
    <DefaultLayout>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <ChatArea
          content={content}
          setContent={setContent}
          queries={queries}
          setQueries={setQueries}
        />
      </div>
    </DefaultLayout>
  );
}
